apps/apps/news/urls.py
from .views import *
from django.conf.urls import patterns, url

urlpatterns = [
    url(r'^detail/(?P<id>\d+)/', NewsDetailView.as_view(), name='news_detail'),
]

apps/urls.py
from main.views import RulesView
from django.contrib import admin
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.flatpages import views
from django.views.generic.base import TemplateView

from news.views import NewsListView

urlpatterns = patterns('',
    url(r'^$', NewsListView.as_view(), name='index'),
    url(r'^rules/$', RulesView.as_view(), name='rules'),
    url(r'^tourney/', include('tourney.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^news/', include('news.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^med/', include('media.urls'))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^translation/$', views.flatpage, {'url': '/translation/'}, name='translation'),

]

apps/apps/news/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.contrib.auth.models import User
from easy_thumbnails.fields import ThumbnailerImageField
from tourney.models import City
from ckeditor.fields import RichTextField
from django.utils.translation import ugettext_lazy as _

from django.db import models


TYPE = (
    ('russian_bowl', _(u"Кубок России")),
    ('region_bowl', _(u"Региональные Кубки")),
    ('online_qualifying', _(u"Онлайн Отборочные")),
)


class Article(models.Model):
    title = models.CharField(max_length=500, verbose_name=_(u"Заголовок"))
    main_image = ThumbnailerImageField(blank=True, verbose_name=_("Превью Статьи"))
    short_article = RichTextField(verbose_name=_(u"Краткое Содержание"))
    article = RichTextField(verbose_name=_(u"Статья"))
    author = models.ForeignKey(User, blank=True, null=True, verbose_name=_(u"Автор"))
    created_at = models.DateField(auto_now_add=True, verbose_name=_(u"Создано"))
    type = models.CharField(max_length=100, choices=TYPE, verbose_name=_(u"Тип Статьи"))
    city = models.ForeignKey(City, blank=True, null=True, verbose_name=_(u"Город"))

    @staticmethod
    def get_news():
        return Article.objects.filter(city=None).order_by('-pk')

    class Meta:
        verbose_name = _("Новости")
        verbose_name_plural = _("Статья")

apps/apps/news/views.py
# -*- coding: utf-8 -*-
from .models import Article

from django.views.generic import ListView
from django.views.generic.base import TemplateView


class NewsView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super(NewsView, self).get_context_data(**kwargs)
        context["nav_news"] = True
        return context


class NewsListView(ListView):
    template_name = "news/news.html"
    model = Article
    context_object_name = "news"
    paginate_by = 5

    def get_queryset(self):
        return Article.get_news()

    def get_context_data(self, **kwargs):
        context = super(NewsListView, self).get_context_data(**kwargs)
        context["nav_news"] = True
        return context


class NewsDetailView(NewsView):
    template_name = "news/detail.html"

    def get_context_data(self, **kwargs):
        context = super(NewsDetailView, self).get_context_data(**kwargs)
        context["article"] = Article.objects.get(id=kwargs['id'])

        return context

apps/templates/news/base.html
{% extends 'base.html' %}

{% load staticfiles %}

<!-- JUMBOTRON -->
{% block main %}

    <section class="section np-b cp" onClick="window.open('http://www.yota.ru');">
        <div class="container-fluid">
            <div class="jumbotron" style="background: url('{% static 'img/banner_for_main.png'%}') center center no-repeat;"></div>
        </div><!-- container -->
    </section>

    <section class="section wrapp">
        {% block main-news %}

        {% endblock %}
    </section>
    <!-- JUMBOTRON -->
    <section class="section np-t cp" onClick="window.open('http://www.yota.ru');">
        <div class="container-fluid">
            <div class="jumbotron" style="background: url('{% static 'img/banner_for_main.png'%}') center center no-repeat;"></div>
        </div><!-- container -->
    </section>
{% endblock %}

apps/templates/news/detail.html
{% extends 'news/base.html' %}

{% load staticfiles %}

{% block main-news %}
<div class="container-fluid">
  <!-- BREADCRUMB -->
  <div class="row">
      <div class="col-md-12">

          <ol class="breadcrumb">
              <li><a href="/">Новости</a></li>
              <li class="active">{{ article.title }}</li>
          </ol>
      </div>
  </div>
  <div class="row">
      <div class="col-md-8">

          <!-- CONTENT TITLE -->
          <div class="title">
              <h1>Новости</h1>
          </div>

          <!-- NEWS -->
          <div class="news">
              <div class="news-meta">
                  <span class="label label-default">{{ article.get_type_display }}</span>
                  <span class="date">{{ article.created_at }}</span>
              </div>
              <div class="news-title">
                  <h2>{{ article.title }}</h2>
              </div>
              <div class="news-body">
                  {% if article.main_image %}
                      <img src="{{ article.main_image.url }}" alt="" class="news-baner">
                  {% endif %}
                  <article>
                      {{ article.article|safe }}
                  </article>
              </div>
              <div class="clear"></div>
          </div>

          <!-- TITLE -->
          <div class="title">
              <h2>Комментарии</h2>
          </div>

          <!-- COMMENTS -->
          <div class="comments">
            <!-- Put this script tag to the <head> of your page -->
            <script type="text/javascript" src="//vk.com/js/api/openapi.js?121"></script>

            <script type="text/javascript">
              VK.init({apiId: 5388576, onlyWidgets: true});
            </script>

            <!-- Put this div tag to the place, where the Comments block will be -->
            <div id="vk_comments"></div>
            <script type="text/javascript">
            VK.Widgets.Comments("vk_comments", {limit: 10, attach: "*"});
            </script>
          </div>
      </div><!-- col -->
      <div class="col-md-4">
        {% include "sidebar.html" %}
      </div><!-- col -->
  </div><!-- row -->
</div><!-- container -->
{% endblock %}

apps/templates/news/news.html
{% extends 'news/base.html' %}

{% load staticfiles misc tourney %}

{% block main-news %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <!-- CONTENT TITLE -->
                <div class="title">
                    <h1>Новости</h1>
                </div>
                <!-- NEWS -->
                {% for article in news %}
                    <div class="news">
                        <div class="news-meta">
                            <span class="label label-default">{{ article.get_type_display }}</span>
                            <span class="date">{{ article.created_at }}</span>
                        </div>
                        <div class="news-title">
                            <h2><a href="{% url 'news_detail' article.pk %}" class="next">{{ article.title }}</a></h2>
                        </div>
                        <div class="news-body">
                            {% if article.main_image %}
                                <img src="{{ article.main_image.url }}" alt="" class="news-baner">
                            {% endif %}
                            <article>
                                {{ article.short_article|safe }}
                            </article>
                            <a href="{% url 'news_detail' article.pk %}" class="next">Читать далее →</a>
                        </div>
                        <div class="clear"></div>
                    </div>
                {% endfor %}
                <!-- NEWS -->
                {% if is_paginated %}
                    <nav class="pagi">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                <li>
                                    <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">&larr; Назад</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="disabled">
                                    <a href="#" aria-label="Previous">
                                        <span aria-hidden="true">&larr; Назад</span>
                                    </a>
                                </li>
                            {% endif %}
                            {% for i in page_obj.paginator.num_pages|get_paginator_range %}
                                <li {% if page_obj.number == i %} class="disabled active" {% endif %}><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li>
                                    <a href="?page={{ page_obj.next_page_number }}" aria-label="Previous">
                                        <span aria-hidden="true">Вперед &rarr;</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="disabled">
                                    <a href="#" aria-label="Previous">
                                        <span aria-hidden="true">Вперед &rarr;</span>
                                    </a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endif %}

            </div><!-- col -->
            <div class="col-md-4">
                {% include "sidebar.html" %}
            </div><!-- col -->
        </div><!-- row -->
    </div><!-- container -->
{% endblock %}